[workspace]
members = [
    "include_wesl",
    "include_wesl_macros"
]

resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.88"
version = "0.1.0"

[workspace.dependencies]

# Internal dependencies

include_wesl_macros = { path = "include_wesl_macros" }

# External dependencies

bincode = { version = "2.0.1", default-features = false, features = [ "serde" ] }
naga = { version = "30.0.1", default-features = false }
proc-macro2 = { version = "1", default-features = false }
quote = { version = "1", default-features = false, features = [ "proc-macro" ] }
rustversion = { version = "1.0.14", default-features = false }
syn = { version = "3.0.6", default-features = false }
wesl = { version = "0.6.0", default-features = false, features = [ "naga-ext" ] }
wgpu = { version = "30.0.1", default-features = false, features = [ "naga-ir" ] }

[patch.crates-io]
wesl = { git = "https://github.com/DouglasDwyer/wesl-rs", rev = "77392d0f903e18e6d75b876e7e2cea31867a35f6" }

[workspace.lints.clippy]
missing_docs_in_private_items = "warn"
unwrap_used = "warn"

[workspace.lints.rust]
missing_docs = "warn"
